### ISSUE TITLE
Remove GitHub client ID and Secret from Query Strings

### ISSUE THREAD

**Issue by danishkhan** [travis-ci/gh#21]
When using GitHub Basic Auth there is no need for the `client_id` or `client_secret`, so we should clean up the API calls to remove them from the query string

https://github.com/travis-ci/gh/blob/27e30fd01f6d5144d8d7d0c88db7875b95ed8939/lib/gh/token_check.rb#L21

/cc @rkh

**Comment by shawnzhu** [comment]
Any update on this?

**Comment by shawnzhu** [comment]
@danishkhan @rkh I've also found these code: https://github.com/travis-ci/gh/blob/master/lib/gh/custom_limit.rb#L18-L21

It means `client_secret` will be exposed as query string in API calls to github.com or GitHub Enterprise app which will be recorded in HTTP access log, so that this piece of information will be shared in clear text. This is totally unexpected.

When revisiting [GitHub API doc](https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app), I didn't see any usage that requires `client_secret` in query string. So is this ok that remove the above mentioned code?

**Comment by BanzaiMan** [comment]
I blieve #38 closed this.
